baseurl: https://www.mattlincoln.net
languageCode: en
theme: hugo-theme-stack
paginate: 5
title: Matt Lincoln - Salesforce, Pardot & Martech Blog

# Change it to your Disqus shortname before using
disqusShortname: hugo-theme-stack

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn
DefaultContentLanguage: en

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: assets/icons/favicon.ico

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006

    sidebar:
        emoji: 
        subtitle: Breaking stuff in Pardot & writing about it.
        avatar:
            local: true
            src: img/matt-lincoln.jpg

    article:
        math: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: utterances
        utterances:
            repo: cultivateautomation/matt-stack
            issueTerm: pathname
            label: utterance
            theme: preferred-color-scheme

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5
            path: archives

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site: pardotmatt

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: true
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true
        
        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home

        - identifier: about
          name: About
          url: about
          weight: -90
          pre: user

        - identifier: archives
          name: Archives
          url: archives
          weight: -70
          pre: archives

        - identifier: search
          name: Search
          url: search
          weight: -60
          pre: search

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    highlight:
        noClasses: false
