[build]
  command = "hugo"
  publish = "public"

[[headers]]
  for = "/scss/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/ts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
