[build]
    publish = "matt-stack/public"

[build.environment]
    HUGO_VERSION = "0.79.1"
    HUGO_THEME = "repo"

[context.production]
    command = "cd matt-stack && hugo --gc --themesDir ../.. -b ${URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    command = "cd matt-stack && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    command = "cd matt-stack && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[[plugins]]
    package = "/matt-stack/plugins/netlify-plugin-hugo-cache-resources"